url: http://subirrastogi.github.io/portfolio-d/
baseurl: /portfolio-d/

# Site settings
title: Dr Swati
email: your-emai@domain.com
description: "Skincare specialist/ Dermatologist in Amritsar"
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/drswatiarora
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 101, 99 Feet Road Near Mata Kaula Hospital
  - line: Amritsar Punjab 90210

# Build settings
markdown: kramdown
permalink: pretty